Repository bieniu/ha-shellies-discovery-gen2, pull requests merged in 2023-12, with the labels that each got.

#320 Add support for Gen3 devices
  README.md
  info.md
  python_scripts/shellies_discovery_gen2.py
Labels: new-feature

#321 Add support for Pro Dimmer 2
  python_scripts/shellies_discovery_gen2.py
Labels: new-feature

#323 Correct description for humidity vs illuminance
  python_scripts/shellies_discovery_gen2.py
Labels: bugfix

#328 Fix Pro Dimmer 2PM model name and ID
  python_scripts/shellies_discovery_gen2.py
Labels: bugfix

#332 Add Shelly Pro Dimmer 1PM
  python_scripts/shellies_discovery_gen2.py
Labels: new-feature

#335 Add support for Pro 3EM Add-on
  python_scripts/shellies_discovery_gen2.py
Labels: new-feature

#336 Add info about Pro 3EM Switch Add-on
  README.md
  info.md
Labels: documentation

#340 Hardcode wakeup_period
  python_scripts/shellies_discovery_gen2.py
Labels: bugfix
